name: Run Playwright Tests with Allure

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run specific test
        run: npx playwright test tests/saucedemo_login.spec.ts

      - name: Upload Allure Results
        uses: actions/upload-artifact@d8bcd0475a7e254f33b1c43f7ac6ed4525f732fa
        with:
          name: allure-results
          path: allure-results/
